"""`make inspect` — your group, your session, and the two protocols on one page."""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from fixtures.generate import group, health_token, keypair, session, wires

SEED = os.environ.get("FLAG_SEED", "local-dev-seed")


def main() -> None:
    grp = group(SEED)
    key = keypair(SEED)
    ses = session(SEED, "public")
    gate = wires(SEED, "public")

    print("== your group ==")
    print(f"  p = {grp['p']}   q = {grp['q']}   g = {grp['g']}")
    print(f"  the subgroup generated by g has order q = {grp['q']}")
    print()
    print("== the sender's key ==")
    print(f"  A = g^a mod p = {key['public']}")
    print("  (a is the sender's; you never see it, and you cannot recover it from A")
    print("   without solving a discrete log)")
    print()
    print("== your session, as the receiver ==")
    print(f"  choice = {ses['choice']}   blind t = {ses['blind']}")
    print(f"  the sender is offering message_0 = {ses['message_0']} and message_1 = {ses['message_1']}")
    print()
    print("== the transfer ==")
    print("  B = g^t          if you want message 0")
    print("  B = A * g^t      if you want message 1")
    print("  sender replies:  message_0 under key(B^a), message_1 under key((B/A)^a)")
    print("  you decrypt with key(A^t)")
    print()
    print("  Ask yourself which values of B each choice can produce. If some element")
    print("  is reachable under one choice and not the other, the sender can read your")
    print("  choice off the request without breaking anything.")
    print()
    print("== your AND gate ==")
    print(f"  party 0 holds x0 = {gate['x0']}, y0 = {gate['y0']}")
    print(f"  party 1 holds x1 = {gate['x1']}, y1 = {gate['y1']}")
    print(f"  so x = {gate['x0'] ^ gate['x1']} and y = {gate['y0'] ^ gate['y1']}, held by nobody")
    print()
    print("  (x0^x1) & (y0^y1) = x0y0 ^ x1y1 ^ x0y1 ^ x1y0")
    print("  the first two are local; each of the last two costs one transfer")
    print()
    print("  Both masks cancel when the shares are XORed. That is true whether you draw")
    print("  one mask or two, so reconstruction cannot tell you which you should draw.")
    print()
    print(f"health token: {health_token(SEED)}")


if __name__ == "__main__":
    main()
