"""`make inspect` — your group, your session, and the two protocols on one page."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

SEED = os.environ.get("FLAG_SEED", "local-dev-seed")


def _public_payload() -> dict:
    """This deployment's public half -- the same values `verifier/server.py`'s
    `GET /public` serves, and the same ones this file has always printed.

    Issue 537/538 (Issue 543 option B2): `fixtures/generate.py` does not ship in the
    `participant` Docker stage any more (see local/Dockerfile). It shipped beside
    `tests/hidden/check_oblivious.py`, whose assertions decide all six checkpoints --
    including the two properties the problem is actually about, which a learner is meant
    to derive rather than read. `make inspect` now runs through Compose (see the
    Makefile) so this process can reach the verifier over the network instead.
    """
    injected = os.environ.get("PUBLIC_EVIDENCE_JSON")
    if injected:
        return json.loads(injected)
    verifier_public_url = os.environ.get("VERIFIER_PUBLIC_URL")
    if verifier_public_url:
        from urllib.error import HTTPError, URLError
        from urllib.request import urlopen

        try:
            with urlopen(verifier_public_url, timeout=10) as response:  # noqa: S310
                return json.loads(response.read().decode("utf-8"))
        except (HTTPError, URLError, TimeoutError, OSError, ValueError) as error:
            # Compose health-gates the workbench on the verifier, so this normally
            # cannot happen. When it does -- a `docker compose run` against a torn-down
            # deployment -- say which service is missing instead of printing a urllib
            # traceback at somebody trying to read their fixtures.
            raise SystemExit(
                "cannot reach this deployment's verifier "
                f"({verifier_public_url}): {type(error).__name__}.\n"
                "The public evidence lives there since Issue 537/538. "
                "Start it with `make verifier-up` and try again."
            ) from error
    # Neither is set: this resolves only where `fixtures/` is actually on disk -- a
    # checkout, or the verifier/author Docker stage -- and never inside a built
    # `participant` image, so this branch does not reopen the leak above.
    from fixtures.generate import public_payload

    return public_payload(SEED)


def main() -> None:
    payload = _public_payload()
    grp = payload["group"]
    key = payload["senderKey"]
    ses = payload["session"]
    gate = payload["wires"]

    print("== your group ==")
    print(f"  p = {grp['p']}   q = {grp['q']}   g = {grp['g']}")
    print(f"  the subgroup generated by g has order q = {grp['q']}")
    print()
    print("== the sender's key ==")
    print(f"  A = g^a mod p = {key['public']}")
    print("  (a is the sender's; you never see it, and you cannot recover it from A")
    print("   without solving a discrete log)")
    print()
    print("== your session, as the receiver ==")
    print(f"  choice = {ses['choice']}   blind t = {ses['blind']}")
    print(f"  the sender is offering message_0 = {ses['message_0']} and message_1 = {ses['message_1']}")
    print()
    print("== the transfer ==")
    print("  B = g^t          if you want message 0")
    print("  B = A * g^t      if you want message 1")
    print("  sender replies:  message_0 under key(B^a), message_1 under key((B/A)^a)")
    print("  you decrypt with key(A^t)")
    print()
    print("  Ask yourself which values of B each choice can produce. If some element")
    print("  is reachable under one choice and not the other, the sender can read your")
    print("  choice off the request without breaking anything.")
    print()
    print("== your AND gate ==")
    print(f"  party 0 holds x0 = {gate['x0']}, y0 = {gate['y0']}")
    print(f"  party 1 holds x1 = {gate['x1']}, y1 = {gate['y1']}")
    print(f"  so x = {gate['x0'] ^ gate['x1']} and y = {gate['y0'] ^ gate['y1']}, held by nobody")
    print()
    print("  (x0^x1) & (y0^y1) = x0y0 ^ x1y1 ^ x0y1 ^ x1y0")
    print("  the first two are local; each of the last two costs one transfer")
    print()
    print("  Both masks cancel when the shares are XORed. That is true whether you draw")
    print("  one mask or two, so reconstruction cannot tell you which you should draw.")
    print()
    print(f"health token: {payload['healthToken']}")


if __name__ == "__main__":
    main()
