#!/bin/sh
#
# One-shot init for wp-harden-leaks. Two jobs, in this order:
#
#   1. plant the previous operator's four leftovers into the docroot;
#   2. make the site a working WordPress install (not the setup wizard);
#
# and then, only once both have succeeded, write the marker the verify container waits
# for. NO flags are planted — judging is state-based (the verify container probes the
# live site). One hole (debug.log) is designed to REGENERATE unless WP_DEBUG is turned
# off, so a naive delete does not close it.
#
# ## Why the planting lives here and not in the wordpress image
#
# The participant gets a shell in the wordpress container, so anything in that image is
# readable by them. This script names all four leaks and their exact paths, which is the
# thing the problem asks them to work out. `wpinit` does not share its image with the
# container the participant can enter, so the scenario setup stays out of reach without
# changing what the participant can do.
#
# ## Why the marker exists
#
# The verify container is an external scanner: it calls a hole CLOSED when the surface is
# no longer reachable. An unseeded site looks exactly like a perfectly remediated one, so
# if scoring could start before this script finished, every checkpoint would pass and the
# participant would be handed all 200 points for doing nothing. The marker makes that
# race impossible to lose silently: no marker, no scoring.
set -e

DOCROOT="/var/www/html"
MARKER="${DOCROOT}/.tenkacloud-seeded"
FLAG_SEED="${FLAG_SEED:-local-dev-seed}"
ADMIN_PW="admin-$(printf '%s' "admin:${FLAG_SEED}" | sha256sum | cut -c1-16)"

# The DB is already up (compose depends_on: db service_healthy) and the WordPress core
# files are present (wordpress is service_healthy = Apache accepting, which only happens
# after the stock entrypoint copies core into the shared volume). Poll version.php as a
# cheap belt-and-suspenders. We do NOT use `wp db check` (needs the mysql client the
# wordpress:cli image doesn't bundle); every command talks to the DB through PHP's mysqli.
echo "wpinit: waiting for WordPress core files..."
until [ -f /var/www/html/wp-includes/version.php ]; do sleep 3; done

# The marker is cleared first so a restart cannot be scored against a half-seeded site
# using the previous run's marker.
rm -f "${MARKER}"

echo "wpinit: planting the previous operator's leftovers..."
mkdir -p "${DOCROOT}/wp-content/backups" "${DOCROOT}/wp-content/mu-plugins" "${DOCROOT}/internal"

# A robots.txt that tries to "hide" the leftover folders — which, of course, only
# advertises exactly where to look. Kept as a breadcrumb; robots.txt is not access control.
cat > "${DOCROOT}/robots.txt" <<'ROBOTS'
User-agent: *
Disallow: /wp-admin/
Disallow: /wp-content/backups/
Disallow: /internal/
ROBOTS

# --- hole: close-backup -------------------------------------------------------
# A full DB dump the previous operator left in a public folder. Static SQL text
# (single-quoted heredoc = no expansion of the $P$B hash / table names).
cat > "${DOCROOT}/wp-content/backups/db-backup.sql" <<'SQL'
-- Aoi Corp WordPress database backup
-- Generated by the previous operator during the site migration.
-- TODO(before launch): move this OUT of the public web root. (never done)
INSERT INTO `wp_users` VALUES
  (1,'admin','$P$Bf7Hs9kExampleHashNotRealDoNotUse01','admin@aoi-corp.example','Administrator');
INSERT INTO `wp_options` VALUES
  (1,'siteurl','http://www.aoi-corp.example'),(2,'blogname','Aoi Corp');
SQL

# --- hole: close-config -------------------------------------------------------
# An editor backup of wp-config.php. Apache serves .bak as plain text — PHP only runs
# .php — so the DB credentials leak verbatim.
cat > "${DOCROOT}/wp-config.php.bak" <<'CONFIG'
<?php
// wp-config.php.bak — saved by the previous operator before the migration edits.
// TODO: delete this editor backup. It is served as PLAIN TEXT from the web root.
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'db:3306' );
$table_prefix = 'wp_';
require_once ABSPATH . 'wp-settings.php';
CONFIG

# --- hole: close-debug (the trap) ---------------------------------------------
# WP_DEBUG is on (WORDPRESS_DEBUG) and WP_DEBUG_LOG is on (WORDPRESS_CONFIG_EXTRA). This
# must-use plugin emits a notice on every request, so WordPress rewrites wp-content/debug.log
# each time the site is hit — deleting the file alone loses; the real fix is to turn WP_DEBUG
# off in wp-config.php (the literal line), then delete the file.
cat > "${DOCROOT}/wp-content/mu-plugins/zz-ops-notice.php" <<'PHP'
<?php
/**
 * Left enabled by the previous operator. While WP_DEBUG + WP_DEBUG_LOG are on, this
 * writes to wp-content/debug.log on every request. Turning the debug setting off (not
 * just deleting the log) is the real fix.
 */
add_action( 'init', static function () {
    trigger_error( 'ops housekeeping tick', E_USER_NOTICE );
} );
PHP

# A starting debug.log so the hole is already open before the first request.
cat > "${DOCROOT}/wp-content/debug.log" <<'LOG'
[02-Jul-2026 09:15:22 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called incorrectly.
[02-Jul-2026 09:16:01 UTC] [ops] reminder: turn WP_DEBUG OFF before launch.
LOG

# --- hole: close-listing ------------------------------------------------------
# An "internal" folder left browsable via Apache directory listing. The listing itself is
# switched on in the wordpress image's Dockerfile (conf-available + a2enconf), because it
# is Apache configuration rather than a docroot file.
cat > "${DOCROOT}/internal/handover.txt" <<'HANDOVER'
Aoi Corp — 引き継ぎメモ / handover notes (internal, DO NOT publish)

This folder was meant to be internal only, but it sits in the public web root and
directory listing is on, so anyone can browse it. Close it: disable the listing,
add an index.html, or remove the folder.
HANDOVER

# This container runs as uid 33 (www-data), the same user Apache runs as, so everything
# written above is already owned correctly. The explicit modes keep the static leftovers
# readable and let Apache re-create wp-content/debug.log after the player deletes it,
# which is what makes the debug trap a trap.
chmod -R a+rX "${DOCROOT}/wp-content/backups" "${DOCROOT}/internal"
chmod a+r "${DOCROOT}/robots.txt" "${DOCROOT}/wp-config.php.bak"
chmod a+rw "${DOCROOT}/wp-content/debug.log"

if wp core is-installed --allow-root >/dev/null 2>&1; then
  echo "wpinit: already installed; leftovers refreshed."
else
  # ポートを焼き込まない (Issue 399)。実際の配信 URL は wp-config.php の WP_HOME /
  # WP_SITEURL が Host から毎回決めるので、ここは install を通すための値でよい。
  wp core install --allow-root \
    --url="http://localhost" \
    --title="Aoi Corp" \
    --admin_user="admin" \
    --admin_password="${ADMIN_PW}" \
    --admin_email="admin@aoi-corp.example" \
    --skip-email

  wp option update blogdescription "デザインと印刷のご相談承ります" --allow-root
  wp post create --allow-root --post_status=publish \
    --post_title="ごあいさつ" \
    --post_content="Aoi Corp のコーポレートサイトへようこそ。お問い合わせはフォームからどうぞ。"
  wp post create --allow-root --post_status=publish \
    --post_title="サイトをリニューアルしました" \
    --post_content="このたびサイトを移行しました。今後ともよろしくお願いいたします。"
fi

# Last line of the script on purpose: `set -e` means any failure above leaves the marker
# absent, and an absent marker stops the verifier from scoring at all.
printf 'seeded\n' > "${MARKER}"
echo "wpinit: done."
