"""Implement a toy 1-out-of-2 oblivious transfer.

This is an independently designed teaching API. It mirrors the meaning of the
course's Part B inputs without copying its function or file names.

The group is the order-233 subgroup generated by 4 modulo 467. Messages are
16-bit integers. These tiny parameters are for observation, not security.
"""

from __future__ import annotations

import hashlib

GROUP_PRIME = 467
GROUP_ORDER = 233
GENERATOR = 4
MESSAGE_MAX = (1 << 16) - 1


def _pad(shared: int, branch: int) -> int:
    """Map one branch key to the exact 16-bit pad used by this lab."""
    digest = hashlib.sha256(f"tc-ot-v1:{shared}:{branch}".encode()).digest()
    return int.from_bytes(digest[:2], "big")


def make_receiver_request(
    sender_public: int, choice: int, receiver_secret: int
) -> int:
    """Return the receiver's one group element.

    choice is 0 or 1. The request must let the receiver derive one key while
    leaving the two choices with the same observable distribution.
    """
    raise NotImplementedError


def seal_sender_messages(
    sender_secret: int,
    request: int,
    message_0: int,
    message_1: int,
) -> tuple[int, int]:
    """Encrypt both messages as message_i XOR _pad(branch_key_i, i)."""
    raise NotImplementedError


def open_receiver_message(
    sender_public: int,
    choice: int,
    receiver_secret: int,
    ciphertexts: tuple[int, int],
) -> int:
    """Recover exactly the selected message with the supplied _pad helper."""
    raise NotImplementedError
