import type { HintContext, HintText } from './hints.ts';
import { ECDSA_MULTIPLES, ENIGMA_WHEEL } from './evolution-model.ts';
import { starkPolynomials } from './stark.ts';

const pair = (ja: string, en: string): HintText => ({ja,en});
const remainder = (p: number) => pair(`各計算の後、負なら${p}を足し、${p}以上なら${p}を引き、0〜${p-1}にします。`, `After each calculation, add ${p} if negative or subtract ${p} if at least ${p}, repeating until 0–${p-1}.`);
/** Paid steps use only this team's displayed task. Leave the submitted result to the player. */
export function advancedHints(ctx: HintContext, level: number): HintText | undefined {
 const t=ctx.task;
 const ladder=(a:HintText,b:HintText,c:()=>HintText)=>level===0?a:level===1?b:level===2?c():undefined;
 switch(t.kind){
 case 'ssm-decrypt': return ladder(
  pair('AWSで鍵を取得し、暗号文から鍵を引いて元の数字へ戻します。復号した数字1個と、取得したValue全体を送ります。','Retrieve the key in AWS and subtract it from the ciphertext. Submit one recovered digit and the complete retrieved Value.'),
  pair('式：平文 = 暗号文 − 鍵。負なら10を足します。\n① 暗号文2−鍵5=−3\n② 負なので10を足す：−3+10=7\n③ この例の平文は7。receiptは計算に使いません。','Rule: plaintext = ciphertext − key; add 10 if negative.\n1. Ciphertext 2 minus key 5 = −3.\n2. Add 10: −3+10=7.\n3. The example plaintext is 7. Do not calculate with receipt.'),
  ()=>pair(`① 「AWSで鍵の値を見る」を開く。\n② Value全体を「Valueの全体をコピーして貼る」へ貼る。\n③ Valueのkeyの数字をkとして、${t.ciphertext}−k=□。\n④ □が負なら10を足す。\n⑤ 結果を「復号した数字（0〜9）」へ入れ、「答えを送ってアイテムを獲得」。`, `1. Open Read the key in AWS.\n2. Paste its complete Value in Paste the complete Value.\n3. Use the key number as k: ${t.ciphertext}−k=□.\n4. Add 10 if negative.\n5. Enter the result in Decrypted digit (0–9), then Submit to acquire the item.`));
 case 'enigma-encrypt': return ladder(
  pair('車輪の表を往復して、元の数字を別の数字へ変えます。反射板で折り返します。このお題は暗号化1回で完了します。','Encrypt one digit by following the wheel lookup out and back, turning at the reflector. One encryption completes this Order.'),
  pair('手順：最初に車輪を1進めます。今回の位置 = (初期位置+1)を4で割った余り。画面の今回の表で、元の数→往路→反射板→逆路の順にたどります。逆路は表の右から左へ読みます。\n例：初期位置3なら今回の位置0。車輪が0→1、1→3、2→0、3→2。\n① 元の0を左→右：1\n② 反射板で1→0\n③ 右側が0の行を探す：左側は2\n④ この例の答えは2。','Rule: advance first; current position is (initial+1) remainder 4. Use the current lookup on screen: original → forward → reflector → reverse. Read right to left on the reverse trip.\nExample: initial position 3 advances to 0; wheel 0→1, 1→3, 2→0, 3→2.\n1. Original 0 goes forward to 1.\n2. Reflect 1 to 0.\n3. Find 0 on the right; its left number is 2.\n4. The example answer is 2.'),
  ()=>{const pos=(t.initial+1)%4; const wiring=[0,1,2,3].map(m=>`${m}→${(ENIGMA_WHEEL[(m+pos)%4]!-pos+4)%4}`).join(' / ');return pair(`① 初期位置${t.initial}を1進めた今回の位置は${pos}。\n② 今回の表：${wiring}\n③ 左側の${t.plaintext[0]}を探し、右側の数字をメモ。\n④ メモが0なら1、1なら0、2なら3、3なら2へ替える。\n⑤ ④の数字を表の右側で探す。左側の数字を「答えの数字1個」へ入れ、「計算した答えを提出」。`,`1. Advance initial position ${t.initial}: use position ${pos}.\n2. Current lookup: ${wiring}\n3. Find ${t.plaintext[0]} on the left; note the right number.\n4. Swap 0→1, 1→0, 2→3 or 3→2.\n5. Find that result on the right; enter its left number in One answer digit and Submit calculated answer.`);});
 case 'rsa-decrypt': return ladder(
  pair('秘密鍵の回数だけ暗号文を掛けて、元の数字に戻します。このお題は復号だけ。暗号化の提出はありません。','Multiply copies of the ciphertext as directed by the private exponent to recover the original. This is a decryption-only Order.'),
  pair('式：m = c^d mod n。暗号文cを秘密鍵dの回数掛け、nで割った余りが元の数mです。\n例：暗号文8、割る数15、3乗。\n① 8×8=64 → 15で割った余り4\n② 4×8=32 → 15で割った余り2\n③ この例の平文は2。','Formula: m = c^d mod n. Multiply d copies of ciphertext c; the remainder after division by n is original m.\nExample: ciphertext 8, divisor 15, exponent 3.\n1. 8×8=64 → remainder 4.\n2. 4×8=32 → remainder 2.\n3. The example plaintext is 2.'),
  ()=>pair(`① ${t.ciphertext}×${t.ciphertext}=□\n② ①を${t.n}で割った余りをAとする。\n③ A×${t.ciphertext}=□\n④ ③を${t.n}で割った余りを「答えの数字1個」へ入れる。\n⑤ 「計算した答えを提出」で完了。`,`1. ${t.ciphertext}×${t.ciphertext}=□.\n2. Call its remainder after division by ${t.n} A.\n3. A×${t.ciphertext}=□.\n4. Enter its remainder after division by ${t.n} in One answer digit.\n5. Submit calculated answer to finish.`));
 case 'ecdsa-sign': return ladder(
  pair('署名は、中身を隠す暗号化とは別です。メッセージ値hに対応する2個の数字r・sを作り、公開鍵で確認できるようにします。','Signing is different from hiding a message. Calculate two signature numbers r and s for message value h, so a public key can check them.'),
  pair('式：rは表kGの左の座標。s = k⁻¹ × (h + d × r) を7で割った余り。k⁻¹は下で説明する逆元です。\n例：h=1,d=2,k=2。\n① 表のj=2の列：jG=(1,3)、逆元4。逆元は掛けて7の余りが1になる数（2×4=8 → 1）。左の数r=1。\n② d×r=2×1=2\n③ h+②=1+2=3\n④ 逆元×③=4×3=12\n⑤ 7で割った余りs=5。例の署名はr=1,s=5。','Formula: r is the left coordinate of kG. s is k⁻¹ × (h + d × r), reduced by 7. k⁻¹ is the inverse explained below.\nExample h=1,d=2,k=2.\n1. Column j=2 has jG=(1,3), inverse 4; r=1. An inverse multiplies its number to leave remainder 1 (2×4=8 → 1).\n2. d×r=2×1=2.\n3. h+2=3.\n4. 4×3=12.\n5. Remainder by 7 gives s=5. Example signature: r=1,s=5.'),
  ()=>{const point=ECDSA_MULTIPLES[t.k]!; return pair(`① 表のj=${t.k}の列、jG=(${point[0]},${point[1]})を読む。左の数をr欄へ写す。\n② 同じ列の「j⁻¹ mod7」をメモしてIとする。\n③ ${t.d}×r=□A\n④ ${t.hash}+A=□B\n⑤ I×B=□C\n⑥ Cを7で割った余りをs欄へ入れ、「計算した答えを提出」。`,`1. In column j=${t.k}, read jG=(${point[0]},${point[1]}). Copy its left coordinate to r.\n2. Note j⁻¹ mod7 in the same column as I.\n3. ${t.d}×r=□A.\n4. ${t.hash}+A=□B.\n5. I×B=□C.\n6. Enter C's remainder by 7 in s, then Submit calculated answer.`);});
 case 'ec-add': return ladder(
  pair('2点P・Qから新しい点を求めます。座標をそのまま足す操作ではありません。傾きλ、答えのx、答えのyの順に計算します。','Combine points P and Q using the curve rule, not coordinate-wise addition. Calculate slope λ, then result x, then result y.'),
  pair('式：x座標が異なるP=(x1,y1),Q=(x2,y2)では、λ=(y2−y1)×(x2−x1)の逆元、x=λ²−x1−x2、y=λ×(x1−x)−y1。各計算を7で割った余りにします。逆元は下の例で説明します。\n例：P=(2,1),Q=(3,1)。\n① 分母3−2=1。逆元は掛けて7の余りが1になる数。1の逆元は1。\n② 傾きλ=(1−1)×1=0\n③ x=0×0−2−3=−5 → 7を足して2\n④ y=0×(2−2)−1=−1 → 7を足して6\n⑤ 例の入力は「2 6」。\n同一点を足す場合：λ=(3×x1²+2)×(2×y1)の逆元。x,yは上と同じ式です。\n例：P=Q=(2,1)。分母2の逆元は4（2×4=8、余り1）。分子3×2×2+2=14、余り0。λ=0×4=0。x=0−2−2=−4→3。y=0×(2−3)−1=−1→6。入力は「3 6」。\nx座標が同じでyの和が7の倍数なら、打ち消す点O。例：(2,1)+(2,6)=O。Oを足すともう一方の点のままです。','For P=(x1,y1),Q=(x2,y2) with different x coordinates: λ=(y2−y1) times the inverse of (x2−x1); x=λ²−x1−x2; y=λ×(x1−x)−y1. Reduce each result by 7. The example below explains inverses.\nExample P=(2,1),Q=(3,1).\n1. Denominator 3−2=1. An inverse multiplies its number to leave remainder 1 by 7; inverse of 1 is 1.\n2. λ=(1−1)×1=0.\n3. x=0×0−2−3=−5 → add 7 to get 2.\n4. y=0×(2−2)−1=−1 → add 7 to get 6.\n5. Example input: 2 6.\nFor doubling: λ=(3×x1²+2) times the inverse of (2×y1). Use the same x,y formulas above.\nExample P=Q=(2,1): denominator 2 has inverse 4 (2×4=8, remainder 1). Numerator 3×2×2+2=14, remainder 0. λ=0×4=0. x=0−2−2=−4→3; y=0×(2−3)−1=−1→6. Enter 3 6.\nEqual x and a y sum divisible by 7 cancel to O: (2,1)+(2,6)=O. Adding O leaves the other point unchanged.'),
  ()=>{const p=t.left,q=t.right;if(!p||!q){const other=p??q;return pair(other?`① Oは足しても変わらない点です。\n② もう一方の点(${other[0]},${other[1]})を、xとyの間に半角スペースを入れて回答欄へ写す。\n③ 「点を提出」。`:'① O+O=O。\n② 回答欄に英大文字のOを入れ、「点を提出」。',other?`1. Adding O leaves the other point unchanged.\n2. Copy (${other[0]},${other[1]}) into the answer as x space y.\n3. Submit point.`:'1. O+O=O.\n2. Enter capital O and Submit point.');}
   if(p[0]===q[0]&&(p[1]+q[1])%7===0)return pair(`① x座標は両方${p[0]}。\n② yの和${p[1]}+${q[1]}は7の倍数。\n③ 打ち消し合うので回答欄へOを入れ、「点を提出」。`,`1. Both x coordinates are ${p[0]}.\n2. The y sum ${p[1]}+${q[1]} is a multiple of 7.\n3. They cancel. Enter O and Submit point.`);
   const denom=p[0]===q[0]?`2×${p[1]}`:`${q[0]}−${p[0]}`;const numerator=p[0]===q[0]?`3×${p[0]}×${p[0]}+2`:`${q[1]}−${p[1]}`;return pair(`① 分母D=${denom}を計算して7で割った余りにする。\n② 逆元表の「数」でDを探す。その下の逆元をIとする。\n③ 分子N=${numerator}を計算。\n④ λ=N×Iの7で割った余り。\n⑤ x=λ×λ−${p[0]}−${q[0]}の7で割った余り。\n⑥ y=λ×(${p[0]}−x)−${p[1]}の7で割った余り。\n⑦ xとyを半角スペースで区切り「点を提出」。\n${remainder(7).ja}`,`1. Calculate denominator D=${denom}; take its remainder by 7.\n2. Find D in the Number row; call the Inverse below it I.\n3. Numerator N=${numerator}.\n4. λ is N×I remainder 7.\n5. x is λ×λ−${p[0]}−${q[0]} remainder 7.\n6. y is λ×(${p[0]}−x)−${p[1]} remainder 7.\n7. Enter x space y and Submit point.\n${remainder(7).en}`);});
 case 'snark-constraints':return ladder(
  pair('提出された計算と配線が一致するかを調べます。各行の計算から提出値を引き、ずれを5個提出します。すべて0に書き替えるお題ではありません。','Inspect proposed calculations and wires. Subtract the proposed values and submit five mismatches. Do not replace every result with zero.'),
  pair('式：足し算のずれ = 左 + 右 − 提出値。掛け算は左 × 右 − 提出値。配線は渡す値 − 受け取る値。各結果を7で割った余りにします。\n① 足し算の例：2+3−5=0（一致）\n② 掛け算の例：3×4−4=8 → 7を引いて1（不一致）\n③ 配線の例：5−6=−1 → 7を足して6（不一致）','Rules: addition mismatch = left + right − proposed; multiplication = left × right − proposed; wire = outgoing − incoming. Reduce each result by 7.\n1. Addition example: 2+3−5=0, agrees.\n2. Multiplication: 3×4−4=8 → subtract 7: 1, disagrees.\n3. Wire: 5−6=−1 → add 7: 6, disagrees.'),
  ()=>{const [a,b,c]=t.rows;const eq=[`${a[0]}+${a[1]}−${a[2]}`,`${b[0]}×${b[1]}−${b[2]}`,`${c[0]}+${c[1]}−${c[2]}`,`${a[2]}−${c[0]}`,`${b[2]}−${c[1]}`];return pair(eq.map((x,i)=>`${i+1}. ${i<3?`行${i+1}`:`配線${i-2}`}：${x}=□ → 7で割った余りをその欄へ。`).join('\n')+`\n${remainder(7).ja}\n5欄を埋めて「検査結果を提出」。`,eq.map((x,i)=>`${i+1}. ${i<3?`Row ${i+1}`:`Wire ${i-2}`}: ${x}=□ → enter the remainder by 7 in that field.`).join('\n')+`\n${remainder(7).en}\nFill all five fields and Submit check results.`);});
 case 'stark-trace':return ladder(
  pair('前の数を2乗する規則と、実行表がどれだけずれるか調べます。2個のずれから式の値を求め、最後に短い式へまとめる計算をします。提出は4個です。','Check mismatches between the recorded trace and repeated squaring. Use two mismatches in an equation, then calculate one folded coefficient. Submit four values.'),
  pair('式：ずれ = 次の数 − 前の数²。ずれをu,vとするとRの定数は2u−v。Q=q0+q1X+q2X²なら折り畳んだ定数はq0+β×q1。すべて7で割った余りです。\n① 実行表2→5のずれ：5−2×2=1\n② 2個のずれu=1,v=3なら：2×1−3=−1 → 余り6\n③ Q=2+3X+4X²、β=2なら：2+2×3=8 → 余り1\nどれも7で割った余りです。','Rules: mismatch = next − previous². For mismatches u,v, the constant of R is 2u−v. For Q=q0+q1X+q2X², the folded constant is q0+β×q1. Reduce by 7.\n1. Trace 2→5 mismatch: 5−2×2=1.\n2. For mismatches u=1,v=3: 2×1−3=−1 → remainder 6.\n3. Q=2+3X+4X² and β=2: 2+2×3=8 → remainder 1.\nUse remainders by 7 throughout.'),
  ()=>{const [a,b,c]=t.trace;const q=starkPolynomials(t).quotient;return pair(`① ${a}×${a}=□A。${b}−Aを7で割った余りを1欄目へ（u）。\n② ${b}×${b}=□B。${c}−Bを7で割った余りを2欄目へ（v）。\n③ 2×u−vを7で割った余りを「Rの定数」へ。\n④ 表示済みのQは、定数${q[0]}、Xに掛かる数${q[1]}。\n⑤ ${t.beta}×${q[1]}=□C。${q[0]}+Cを7で割った余りをβ=${t.beta}の欄へ。\n⑥ 「4個の計算を提出」。\n${remainder(7).ja}`,`1. ${a}×${a}=□A. Enter (${b}−A) remainder 7 in field 1 (u).\n2. ${b}×${b}=□B. Enter (${c}−B) remainder 7 in field 2 (v).\n3. Enter (2×u−v) remainder 7 in Constant of R.\n4. Supplied Q has constant ${q[0]} and X coefficient ${q[1]}.\n5. ${t.beta}×${q[1]}=□C. Enter (${q[0]}+C) remainder 7 in the β=${t.beta} field.\n6. Submit four calculations.\n${remainder(7).en}`);});
 case 'io-equivalence':return ladder(
  pair('2つの計算A・Bの答えを比べます。空欄2個を計算し、全4入力で同じか答えます。その後、同じ公開データが両方から出る組を数えます。','Compare programs A and B. Fill two missing answers and decide whether all four inputs agree. Then count complete published outcomes possible on both sides.'),
  pair('式：入力をxとすると、A(x)=a×x+b、B(x)=a×(x+d)+c。どちらも5で割った余りを比べます。\n① Aの例：2×3+1=7 → 5で割った余り2\n② Bの例：2×(3+1)+0=8 → 余り3\n③ 同じ入力の答えが2と3なら「同じ？」は0。\n④ 回した表が同じでも、Aの確率が0の行は共通の組に数えません。','Rules for input x: A(x)=a×x+b; B(x)=a×(x+d)+c. Compare their remainders after division by 5.\n1. Example A: 2×3+1=7 → remainder 2 by 5.\n2. Example B: 2×(3+1)+0=8 → remainder 3.\n3. Outputs 2 and 3 differ, so enter 0 for equivalent.\n4. Even matching rotated tables do not count as shared when either probability is zero.'),
  ()=>pair(`① Aの空欄：${t.a}×${t.missing[0]}=□A、A+${t.b}=□B。Bを5で割った余りを上のA欄へ。\n② Bの空欄：${t.missing[1]}+${t.d}=□C、${t.a}×C=□D、D+${t.c}=□E。Eを5で割った余りを上のB欄へ。\n③ 上の表を1行ずつ左右で比べる。全4行同じなら「4行すべて同じ答え？」に1、違う行があれば0。\n④ 下の表の□に①・②の答えを入れて考える。\n⑤ r=0,1,2,3の各行で、回した表の数字が全部一致し、両方の確率が0でない行だけに印を付ける。\n⑥ 印の個数を「共通する組の個数（0〜4）」へ入れ、「計算と比較を提出」。`,`1. A's blank: ${t.a}×${t.missing[0]}=□A, A+${t.b}=□B. Enter B remainder 5 in the upper A cell.\n2. B's blank: ${t.missing[1]}+${t.d}=□C, ${t.a}×C=□D, D+${t.c}=□E. Enter E remainder 5 in the upper B cell.\n3. Compare both answers in every upper row. Enter 1 if all four agree, otherwise 0.\n4. Use your two answers in the lower table's blanks.\n5. For each r=0,1,2,3, mark the row only if both rotated tables match completely and neither probability is zero.\n6. Enter the mark count in Number of shared outcomes (0–4), then Submit calculation and comparison.`));
 case "anamorphic-rejection": return anamorphicSteps(t, level);
 default:return undefined;
 }
}

function anamorphicSteps(t: Extract<HintContext['task'], {kind:'anamorphic-rejection'}>, level: number): HintText | undefined {
 const comparisons=t.secretBits.map((bit,i)=>`F(c${i+1}) = ${bit} =? ${t.targetBit}`).join('\n');
 const tickets=t.tickets.filter((_,i)=>t.secretBits[i]===t.targetBit).join(' + ');
 const select=pair(`① 送りたいビットは${t.targetBit}。\n② 秘密の表を1行目から${t.targetBit}と比べる（=? は同じか自分で確かめる印）。\n${comparisons}\n③ 初めて一致した行で止め、その行番号を「送る候補の番号（1〜6）」へ。`, `1. Target bit: ${t.targetBit}.\n2. Compare lookup bits with ${t.targetBit}, starting at row 1 (=? asks you to check equality).\n${comparisons}\n3. Stop at the first match; enter its Candidate number (1–6).`);
 const probability=pair(`① 秘密の表のビットが${t.targetBit}の行に印を付ける。\n② 印の付いた行のくじ枚数だけをメモする。\n③ メモした枚数を足す：${tickets} = □。\n④ 合計を「受理されるくじの合計（3〜9）」へ。`, `1. Mark lookup rows with bit ${t.targetBit}.\n2. Note the ticket count for each marked row.\n3. Add those counts: ${tickets} = □.\n4. Enter Accepted ticket total (3–9).`);
 const decrypt=(a:string,b:string)=>pair(`① 暗号文の左a=${a}、右b=${b}、鍵x=${t.ordinaryKey}。\n② aを${t.ordinaryKey}個掛け、7で割った余りをSとする。\n③ S×1、S×2、…、S×6を順に計算して7で割った余りにする。\n④ 余りが${b}と一致したとき、Sに掛けた数が元の数m。mを復号の回答欄へ。`, `1. Ciphertext left a=${a}, right b=${b}, key x=${t.ordinaryKey}.\n2. Multiply ${t.ordinaryKey} copies of a and call its remainder by 7 S.\n3. Try S×1, S×2, …, S×6, reducing each by 7.\n4. When the remainder equals ${b}, the multiplier is original m. Enter m in the decryption field.`);
 const exampleDecrypt=pair('式：S = a^x を7で割った余り。S×mを7で割った余りがbになるmを探します。a,bは暗号文、xは鍵です。\n例：a=2,b=5,x=2。\n① 2×2=4、7で割った余りS=4\n② 4×1=4 → 余り4（違う）\n③ 4×2=8 → 余り1（違う）\n④ 4×3=12 → 余り5（一致）。例の元の数は3。','Rule: S is a^x reduced by 7. Find m such that S×m has remainder b after division by 7. Ciphertext is (a,b); x is the key.\nExample a=2,b=5,x=2.\n1. 2×2=4 gives S=4.\n2. 4×1 leaves 4: no.\n3. 4×2 leaves 1: no.\n4. 4×3 leaves 5: match. Example original: 3.');
 if(t.exercise==='encrypt')return [pair('ビットは0か1。普通の暗号文の候補から、秘密の表で送りたいビットになる行を選びます。復号の計算はありません。','A bit is 0 or 1. Choose a ciphertext candidate whose secret lookup matches the intended bit. No decryption is required.'),pair('ルール：候補を上から順に見て、秘密の表F(cᵢ)が送りたいビットと一致する最初の番号iを選びます。cᵢは候補iの暗号文、Fは秘密の表です。\n例：送りたいビット1、表は0・1・1。\n① 1行目の0は違うので次へ。\n② 2行目の1が一致。\n③ この例は候補番号2を提出。','Rule: scan from the top and choose the first index i with F(cᵢ) equal to the target bit. cᵢ is candidate i; F is the secret lookup.\nExample target 1, lookup 0,1,1.\n1. Row 1 differs: continue.\n2. Row 2 matches: stop.\n3. Submit candidate number 2 in this example.'),pair(select.ja+'\n④ 候補番号1個を提出して完了。',select.en+'\n4. Submit the single candidate number to finish.')][level];
 if(t.exercise==='decrypt'){const [a,b]=t.candidates[0]!;const factors=Array.from({length:t.ordinaryKey},()=>a).join(' × ')||'1';const trials=[1,2,3,4,5,6].map(m=>`S × ${m} = □ → □`).join('\n');const raw=decrypt(String(a),String(b));const d=pair(raw.ja.replace('② aを'+t.ordinaryKey+'個掛け、',`② (${a}, ${b}) の左の数を使う：${factors} = □。この数を`).replace('③ S×1、S×2、…、S×6を順に計算して7で割った余りにする。',`③ Sに②で求めた余りを入れる。矢印の右は7で割った余り。\n${trials}`),raw.en.replace(`2. Multiply ${t.ordinaryKey} copies of a and call its remainder by 7 S.`,`2. Use the left number of (${a}, ${b}): ${factors} = □. Divide that result by 7 and call the remainder S.`).replace('3. Try S×1, S×2, …, S×6, reducing each by 7.',`3. Substitute your S. After each arrow, enter the remainder by 7.\n${trials}`));return [pair('今回は通常鍵で暗号文を元の数へ戻します。候補選択や確率の回答はありません。','Use the ordinary key to recover one original number. No candidate selection or probability answer is required.'),exampleDecrypt,pair(d.ja+'\n⑤ 「元の数 m（1〜6）」を提出して完了。',d.en+'\n5. Submit Original number m (1–6) to finish.')][level];}
 if(t.exercise==='probability')return [pair('目的のビットが出る候補だけを残します。その候補のくじ枚数を合計します。今回は合計1個の提出です。','Keep candidates matching the target bit and sum their ticket counts. Submit only that total.'),pair('式：候補が選ばれる確率 = その候補のくじ枚数 ÷ 受理される候補のくじ枚数の合計。受理は秘密の表のビットが目的と一致することです。提出するのは、この分母の合計です。\n例：残る候補のくじが1枚・2枚・3枚。\n① 1+2=3\n② 3+3=6\n③ この例の合計は6。確率の分母になる数です。','Formula: probability of a candidate = its ticket count divided by the total tickets of accepted candidates. Accepted means its lookup bit matches the target. Submit that denominator total.\nExample accepted counts: 1,2,3.\n1. 1+2=3.\n2. 3+3=6.\n3. Total 6 is the probability denominator.'),pair(probability.ja+'\n⑤ 合計1個を提出して完了。',probability.en+'\n5. Submit the one total to finish.')][level];
 const selectionExample=anamorphicSteps({...t,exercise:'encrypt'},1)!;
 const probabilityExample=anamorphicSteps({...t,exercise:'probability'},1)!;
 return [pair('旧形式のお題です。候補選択・通常復号・くじの合計の3欄があります。新形式では別々のお題です。','This legacy Order has three fields: selection, ordinary decryption and ticket total. New Orders separate these tasks.'),pair(selectionExample.ja+'\n'+exampleDecrypt.ja+'\n'+probabilityExample.ja,selectionExample.en+'\n'+exampleDecrypt.en+'\n'+probabilityExample.en),pair('【送る試行番号（1〜6）】\n'+select.ja.replace('送る候補の番号','送る試行番号')+'\n【通常のメッセージm】\n'+decrypt('選んだ行の左の数','選んだ行の右の数').ja+'\n【受理されるくじの合計】\n'+probability.ja+'\n3欄を埋めて「選択・復号・確率を提出」。','Trial to send\n'+select.en.replace('Candidate number','Trial to send')+'\nOrdinary message m\n'+decrypt('left number of your selected row','right number of your selected row').en+'\nTotal accepted tickets\n'+probability.en+'\nFill all three fields and Submit selection, decryption and probability.')][level];
}
