import {expect,test} from "bun:test";
import {initialState,applyOp,tick,validateOp,projectForTeam,STREAMING_ORDER_CONFIG,migrateState} from "./reducer.ts";
import {power,verifySchnorr} from "./schnorr.ts";
const create=()=>tick(applyOp(initialState({eventId:"sigma",teamIds:["a","b"],matchSecret:"server-only-randomness"},STREAMING_ORDER_CONFIG),"a",{kind:"start"}),0);
test("commit precedes the unpredictable challenge, public verification awards once",()=>{
  let state=create(); const id="a-c0";
  expect(validateOp(state,"a",{kind:"hunt-sudoku",targetTeamId:"b",generation:1,solution:projectForTeam(state,"b").vault.sudokuSolution}).ok).toBe(false);
  const before=projectForTeam(state,"a").myContracts[0]!;
  expect(before.schnorr!.pending).toBeUndefined();
  expect(validateOp(state,"a",{kind:"schnorr-response",contractId:id,z:0}).ok).toBe(false);
  expect(validateOp(state,"b",{kind:"schnorr-commit",contractId:id,y:13,a:8}).ok).toBe(false);
  const commit={kind:"schnorr-commit" as const,contractId:id,y:13,a:8};
  expect(validateOp(state,"a",commit).ok).toBe(true);
  state=applyOp(state,"a",commit);
  expect(state.teams.a!.score).toBe(0);
  expect(Object.keys(state.contracts.find(c=>c.id===id)!.schnorr!)).toEqual(["y","a","e"]);
  expect(validateOp(state,"a",commit).ok).toBe(false);
  const projected=projectForTeam(state,"a").myContracts[0]!.schnorr!;
  const z=(3+projected.pending!.e*7)%11;
  const response={kind:"schnorr-response" as const,contractId:id,z};
  expect(validateOp(state,"a",response).ok).toBe(true);
  state=applyOp(state,"a",response);
  expect(state.teams.a!.score).toBe(30);
  expect(validateOp(state,"a",response).ok).toBe(false);
  const record=projectForTeam(state,"b").publicLedger.find(a=>a.kind==="proof")!;
  if(record.kind!=="proof")throw new Error("proof missing");
  expect(verifySchnorr(Number(record.publicKey),Number(record.commitment),Number(record.challenge),Number(record.response))).toBe(true);
  expect(Object.keys(record)).not.toContain("x");
  expect(Object.keys(record)).not.toContain("r");
  expect(projectForTeam(state,"b").myContracts.every(c=>c.id!==id)).toBe(true);
  expect(JSON.stringify(projectForTeam(state,"b"))).not.toContain("server-only-randomness");
});
test("wrong response consumes the proof; no response brute force or old Sudoku bypass",()=>{
  let state=create();const id="a-c0";
  expect(validateOp(state,"a",{kind:"prove-sudoku",contractId:id,grid:projectForTeam(state,"a").vault.sudokuSolution}).ok).toBe(false);
  for(const a of [0,5,23,NaN,1.2]) expect(validateOp(state,"a",{kind:"schnorr-commit",contractId:id,y:13,a}).ok).toBe(false);
  state=applyOp(state,"a",{kind:"schnorr-commit",contractId:id,y:13,a:power(2,4)});
  const proof=projectForTeam(state,"a").myContracts[0]!.schnorr!;
  const right=(4+proof.pending!.e*7)%11;
  state=applyOp(state,"a",{kind:"schnorr-response",contractId:id,z:(right+1)%11});
  expect(state.teams.a!.score).toBe(0);
  expect(projectForTeam(state,"a").publicLedger).toHaveLength(0);
  expect(validateOp(state,"a",{kind:"schnorr-response",contractId:id,z:right}).ok).toBe(false);
  expect(validateOp(state,"a",{kind:"schnorr-commit",contractId:id,y:13,a:8}).ok).toBe(false);
});
test("expiry and old matches retain their contracts",()=>{
  let state=create();state=applyOp(state,"a",{kind:"schnorr-commit",contractId:"a-c0",y:13,a:8});
  state=tick(state,60_000);
  expect(validateOp(state,"a",{kind:"schnorr-response",contractId:"a-c0",z:1}).ok).toBe(false);
  const old=initialState({eventId:"legacy",teamIds:["a"],matchSecret:"old"});
  expect(migrateState(old,12).config.proofProtocol).toBeUndefined();
});
