#!/bin/bash
#
# Plant the previous operator's "operational neglect" into the docroot, then start
# WordPress normally. This is a multi-checkpoint problem (TenkaCloud#2252): the
# previous operator left FOUR independent leftovers in the public web root during
# the migration, each a different, very common misconfiguration:
#
#   public-backup   a database dump in a public folder            (/wp-content/backups/db-backup.sql)
#   exposed-config  an editor backup of wp-config served as text  (/wp-config.php.bak)
#   debug-log       WP_DEBUG_LOG left on in production             (/wp-content/debug.log)
#   dir-listing     Apache directory listing left on for a folder (/internal/)
#
# Each leftover carries its own audit passphrase (the flag), derived from the
# per-deploy random FLAG_SEED so nothing secret is committed and every deploy is
# unique. The verify container derives the same values to judge each checkpoint.
# The compose file binds everything to 127.0.0.1 only.
set -e

FLAG_SEED="${FLAG_SEED:-local-dev-seed}"

# Same derivation the verify container uses: TC{<prefix>_<sha256("flag:<id>:<seed>")[:20]>}.
# The checkpoint id is mixed in so each leftover has a distinct, unpredictable flag.
flag_for() {
  hash="$(printf '%s' "flag:${1}:${FLAG_SEED}" | sha256sum | cut -c1-20)"
  printf 'TC{%s_%s}' "${2}" "${hash}"
}
FLAG_PUBLIC_BACKUP="$(flag_for public-backup wpbackup)"
FLAG_EXPOSED_CONFIG="$(flag_for exposed-config wpconfig)"
FLAG_DEBUG_LOG="$(flag_for debug-log wpdebug)"
FLAG_DIR_LISTING="$(flag_for dir-listing wpindex)"

DOCROOT="/var/www/html"
mkdir -p "${DOCROOT}/wp-content/backups" "${DOCROOT}/wp-content" "${DOCROOT}/internal"

# A robots.txt that tries to "hide" the leftover folders — which, of course, only
# advertises exactly where to look. robots.txt is not access control.
cat > "${DOCROOT}/robots.txt" <<'ROBOTS'
User-agent: *
Disallow: /wp-admin/
Disallow: /wp-content/backups/
Disallow: /internal/
ROBOTS

# --- checkpoint: public-backup ------------------------------------------------
# The database dump the previous operator left behind. Static SQL text; the `$P$B`
# password hash and table names are literal (single-quoted heredoc = no expansion).
cat > "${DOCROOT}/wp-content/backups/db-backup.sql" <<'SQL'
-- Aoi Corp WordPress database backup
-- Generated by the previous operator during the site migration.
-- TODO(before launch): move this OUT of the public web root. (never done)
--
-- Table structure for table `wp_users`
--
INSERT INTO `wp_users` VALUES
  (1,'admin','$P$Bf7Hs9kExampleHashNotRealDoNotUse01','admin@aoi-corp.example','Administrator');
--
-- Table structure for table `wp_options`
--
INSERT INTO `wp_options` VALUES
  (1,'siteurl','http://127.0.0.1:18080'),
  (2,'blogname','Aoi Corp');
--
-- Table structure for table `maintenance_notes`
-- (internal ops notes the previous operator kept alongside the data)
SQL
# Unquoted heredoc so ${FLAG_PUBLIC_BACKUP} expands; no backticks so nothing is
# command-substituted.
cat >> "${DOCROOT}/wp-content/backups/db-backup.sql" <<SQL
INSERT INTO maintenance_notes (id, note) VALUES
  (1, 'DB restore / audit passphrase: ${FLAG_PUBLIC_BACKUP}');
SQL

# --- checkpoint: exposed-config -----------------------------------------------
# An editor backup of wp-config.php ("Save As .bak" before editing). Apache serves
# .bak as plain text — PHP only executes .php — so the DB credentials and the ops
# handoff token leak verbatim.
cat > "${DOCROOT}/wp-config.php.bak" <<CONFIG
<?php
// wp-config.php.bak — saved by the previous operator before the migration edits.
// TODO: delete this editor backup. It is served as PLAIN TEXT from the web root.
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'db:3306' );
// ops handoff token (paste into the runbook): ${FLAG_EXPOSED_CONFIG}
\$table_prefix = 'wp_';
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
CONFIG

# --- checkpoint: debug-log ----------------------------------------------------
# WP_DEBUG_LOG left on in production: wp-content/debug.log is world-readable and
# has captured an internal note. Served as plain text.
cat > "${DOCROOT}/wp-content/debug.log" <<LOG
[02-Jul-2026 09:15:22 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called incorrectly.
[02-Jul-2026 09:15:23 UTC] PHP Warning:  Undefined array key "preview" in /var/www/html/wp-includes/query.php
[02-Jul-2026 09:16:01 UTC] [ops] reminder: turn WP_DEBUG_LOG OFF before launch. log audit passphrase: ${FLAG_DEBUG_LOG}
[02-Jul-2026 09:18:44 UTC] PHP Notice:  wp_enqueue_script was called incorrectly.
LOG

# --- checkpoint: dir-listing --------------------------------------------------
# An "internal" folder left with Apache directory listing on, so its contents are
# browsable. The handover memo carries the passphrase.
cat > "${DOCROOT}/internal/handover.txt" <<HANDOVER
Aoi Corp — 引き継ぎメモ / handover notes (internal, DO NOT publish)

This folder was meant to be internal only, but it sits in the public web root and
directory listing is on, so anyone can browse it.

audit passphrase: ${FLAG_DIR_LISTING}
HANDOVER

# Turn Apache directory listing on for /internal only (scoped, not global). The
# base image ships mod_autoindex enabled; this scopes +Indexes to the folder so
# the leftover is browsable the way a misconfigured host would leave it.
cat > /etc/apache2/conf-enabled/zz-internal-autoindex.conf <<'CONF'
<Directory /var/www/html/internal>
    Options +Indexes
    AllowOverride None
    Require all granted
</Directory>
CONF

chmod -R a+rX "${DOCROOT}/wp-content/backups" "${DOCROOT}/internal"
chmod a+r "${DOCROOT}/robots.txt" "${DOCROOT}/wp-config.php.bak" "${DOCROOT}/wp-content/debug.log"

# Hand off to the stock WordPress entrypoint (copies core, writes wp-config, then
# runs the passed command, e.g. apache2-foreground).
exec docker-entrypoint.sh "$@"
