#!/bin/bash
#
# Drop the "operational neglect" into the docroot, then start WordPress normally.
# The previous operator dumped the database into the public web root while testing
# and never removed it — so anyone who finds the file reads the whole DB dump,
# including a maintenance note (the flag). The flag is derived from FLAG_SEED at
# runtime, so nothing secret is committed and each deploy is unique.
set -e

FLAG_SEED="${FLAG_SEED:-local-dev-seed}"
FLAG_HASH="$(printf '%s' "flag:${FLAG_SEED}" | sha256sum | cut -c1-20)"
FLAG="TC{wpbackup_${FLAG_HASH}}"

DOCROOT="/var/www/html"
mkdir -p "${DOCROOT}/wp-content/backups"

# A robots.txt that tries to "hide" the backups folder — which, of course, only
# advertises exactly where to look.
cat > "${DOCROOT}/robots.txt" <<'ROBOTS'
User-agent: *
Disallow: /wp-admin/
Disallow: /wp-content/backups/
ROBOTS

# The database dump the previous operator left behind. Static SQL text; the `$P$B`
# password hash and table names are literal (single-quoted heredoc = no expansion).
cat > "${DOCROOT}/wp-content/backups/db-backup.sql" <<'SQL'
-- Aoi Corp WordPress database backup
-- Generated by the previous operator during the site migration.
-- TODO(before launch): move this OUT of the public web root. (never done)
--
-- Table structure for table `wp_users`
--
INSERT INTO `wp_users` VALUES
  (1,'admin','$P$Bf7Hs9kExampleHashNotRealDoNotUse01','admin@aoi-corp.example','Administrator');
--
-- Table structure for table `wp_options`
--
INSERT INTO `wp_options` VALUES
  (1,'siteurl','http://127.0.0.1:18080'),
  (2,'blogname','Aoi Corp');
--
-- Table structure for table `maintenance_notes`
-- (internal ops notes the previous operator kept alongside the data)
SQL
# The maintenance note carries the flag. Unquoted heredoc so ${FLAG} expands; no
# backticks on this line so nothing is command-substituted.
cat >> "${DOCROOT}/wp-content/backups/db-backup.sql" <<SQL
INSERT INTO maintenance_notes (id, note) VALUES
  (1, 'DB restore / audit passphrase: ${FLAG}');
SQL

chmod -R a+rX "${DOCROOT}/wp-content/backups"
chmod a+r "${DOCROOT}/robots.txt"

# Hand off to the stock WordPress entrypoint (copies core, writes wp-config, then
# runs the passed command, e.g. apache2-foreground).
exec docker-entrypoint.sh "$@"
