#!/bin/bash
#
# Seed the "previous operator's leftovers" into the docroot, then start WordPress. This
# is the REMEDIATION companion to wp-exposed-backup: the site starts already-leaky and
# the player CLOSES each hole. NO flags are planted — judging is state-based (the verify
# container probes the live site). One hole (debug.log) is designed to REGENERATE unless
# WP_DEBUG is turned off, so a naive delete does not close it. The compose file binds
# everything to 127.0.0.1 only.
set -e

DOCROOT="/var/www/html"
mkdir -p "${DOCROOT}/wp-content/backups" "${DOCROOT}/wp-content/mu-plugins" "${DOCROOT}/internal"

# A robots.txt that tries to "hide" the leftover folders — which, of course, only
# advertises exactly where to look. Kept as a breadcrumb; robots.txt is not access control.
cat > "${DOCROOT}/robots.txt" <<'ROBOTS'
User-agent: *
Disallow: /wp-admin/
Disallow: /wp-content/backups/
Disallow: /internal/
ROBOTS

# --- hole: close-backup -------------------------------------------------------
# A full DB dump the previous operator left in a public folder. Static SQL text
# (single-quoted heredoc = no expansion of the $P$B hash / table names).
cat > "${DOCROOT}/wp-content/backups/db-backup.sql" <<'SQL'
-- Aoi Corp WordPress database backup
-- Generated by the previous operator during the site migration.
-- TODO(before launch): move this OUT of the public web root. (never done)
INSERT INTO `wp_users` VALUES
  (1,'admin','$P$Bf7Hs9kExampleHashNotRealDoNotUse01','admin@aoi-corp.example','Administrator');
INSERT INTO `wp_options` VALUES
  (1,'siteurl','http://127.0.0.1:18080'),(2,'blogname','Aoi Corp');
SQL

# --- hole: close-config -------------------------------------------------------
# An editor backup of wp-config.php. Apache serves .bak as plain text — PHP only runs
# .php — so the DB credentials leak verbatim.
cat > "${DOCROOT}/wp-config.php.bak" <<'CONFIG'
<?php
// wp-config.php.bak — saved by the previous operator before the migration edits.
// TODO: delete this editor backup. It is served as PLAIN TEXT from the web root.
define( 'DB_NAME', 'wordpress' );
define( 'DB_USER', 'wordpress' );
define( 'DB_PASSWORD', 'wordpress' );
define( 'DB_HOST', 'db:3306' );
$table_prefix = 'wp_';
require_once ABSPATH . 'wp-settings.php';
CONFIG

# --- hole: close-debug (the trap) ---------------------------------------------
# WP_DEBUG is on (WORDPRESS_DEBUG) and WP_DEBUG_LOG is on (WORDPRESS_CONFIG_EXTRA). This
# must-use plugin emits a notice on every request, so WordPress rewrites wp-content/debug.log
# each time the site is hit — deleting the file alone loses; the real fix is to turn WP_DEBUG
# off in wp-config.php (the literal line), then delete the file.
cat > "${DOCROOT}/wp-content/mu-plugins/zz-ops-notice.php" <<'PHP'
<?php
/**
 * Left enabled by the previous operator. While WP_DEBUG + WP_DEBUG_LOG are on, this
 * writes to wp-content/debug.log on every request. Turning the debug setting off (not
 * just deleting the log) is the real fix.
 */
add_action( 'init', static function () {
    trigger_error( 'ops housekeeping tick', E_USER_NOTICE );
} );
PHP

# A starting debug.log so the hole is already open before the first request.
cat > "${DOCROOT}/wp-content/debug.log" <<'LOG'
[02-Jul-2026 09:15:22 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called incorrectly.
[02-Jul-2026 09:16:01 UTC] [ops] reminder: turn WP_DEBUG OFF before launch.
LOG

# --- hole: close-listing ------------------------------------------------------
# An "internal" folder left browsable via Apache directory listing.
cat > "${DOCROOT}/internal/handover.txt" <<'HANDOVER'
Aoi Corp — 引き継ぎメモ / handover notes (internal, DO NOT publish)

This folder was meant to be internal only, but it sits in the public web root and
directory listing is on, so anyone can browse it. Close it: disable the listing,
add an index.html, or remove the folder.
HANDOVER

# Turn Apache directory listing on for /internal only (scoped, not global). Written to
# conf-available and enabled with a2enconf, so `a2disconf zz-internal-autoindex` is a
# valid fix for the close-listing checkpoint (as well as adding an index.html or removing
# the folder).
cat > /etc/apache2/conf-available/zz-internal-autoindex.conf <<'CONF'
<Directory /var/www/html/internal>
    Options +Indexes
    AllowOverride None
    Require all granted
</Directory>
CONF
a2enconf zz-internal-autoindex >/dev/null

# www-data (Apache) must be able to (re)create wp-content/debug.log so the trap works
# even after the player deletes the file. Keep the static leftovers world-readable.
chown -R www-data:www-data "${DOCROOT}/wp-content"
chmod -R a+rX "${DOCROOT}/wp-content/backups" "${DOCROOT}/internal"
chmod a+r "${DOCROOT}/robots.txt" "${DOCROOT}/wp-config.php.bak"

# Hand off to the stock WordPress entrypoint (copies core, writes wp-config from env
# incl. WORDPRESS_CONFIG_EXTRA, then runs the passed command, e.g. apache2-foreground).
exec docker-entrypoint.sh "$@"
