#!/usr/bin/env bun
/**
 * Generate CERTIFICATION-INDEX.md: every AWS-certification Challenge grouped by
 * the certification it targets, derived from the slug prefix (clf-, saa-, ...).
 *
 * The certification drill set (Issue #45) tags each problem by exam via its slug
 * prefix. This script renders a human-browsable index so an event organizer can
 * pick problems per exam without opening 100+ metadata.json files. Re-run after
 * adding problems:  bun run scripts/build-cert-index.ts  (or --check in CI).
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = new URL("..", import.meta.url).pathname;
const CHALLENGES_DIR = join(REPO_ROOT, "challenges");
const OUT_PATH = join(REPO_ROOT, "CERTIFICATION-INDEX.md");

// Slug prefix -> certification, in study order (foundational -> specialty).
const CERTS: ReadonlyArray<{ prefix: string; title: string }> = [
  { prefix: "clf", title: "Cloud Practitioner (CLF-C02)" },
  { prefix: "aif", title: "AI Practitioner (AIF-C01)" },
  { prefix: "saa", title: "Solutions Architect – Associate (SAA-C03)" },
  { prefix: "dva", title: "Developer – Associate (DVA-C02)" },
  { prefix: "soa", title: "SysOps Administrator – Associate (SOA-C02)" },
  { prefix: "dea", title: "Data Engineer – Associate (DEA-C01)" },
  { prefix: "mla", title: "Machine Learning Engineer – Associate (MLA-C01)" },
  { prefix: "sap", title: "Solutions Architect – Professional (SAP-C02)" },
  { prefix: "dop", title: "DevOps Engineer – Professional (DOP-C02)" },
  { prefix: "scs", title: "Security – Specialty (SCS-C02)" },
  { prefix: "ans", title: "Advanced Networking – Specialty (ANS-C01)" },
  { prefix: "mls", title: "Machine Learning – Specialty (MLS-C01)" },
  { prefix: "pas", title: "SAP on AWS – Specialty (PAS-C01)" },
];

interface Meta {
  id: string;
  name: string;
  difficulty: number;
  estimatedDuration: string;
  i18n?: { en?: { name?: string } };
}

function loadChallenges(): Meta[] {
  return readdirSync(CHALLENGES_DIR)
    .map((slug) => join(CHALLENGES_DIR, slug, "metadata.json"))
    .filter((p) => {
      try {
        return statSync(p).isFile();
      } catch {
        return false;
      }
    })
    .map((p) => JSON.parse(readFileSync(p, "utf8")) as Meta)
    .sort((a, b) => a.id.localeCompare(b.id));
}

function render(metas: Meta[]): string {
  const lines: string[] = [];
  lines.push("# AWS Certification Challenge Index");
  lines.push("");
  lines.push(
    "Hands-on `flag` Challenges mapped to every active AWS certification (Issue #45). " +
      "Each is a free-tier ($0) CloudFormation lab whose flag must be **derived by analysis** " +
      "of the deployed configuration — the answer is never readable by the participant role. " +
      "Generated by `scripts/build-cert-index.ts`; do not edit by hand.",
  );
  lines.push("");

  const used = new Set<string>();
  let total = 0;
  for (const cert of CERTS) {
    const items = metas.filter((m) => m.id.startsWith(`${cert.prefix}-`));
    if (items.length === 0) continue;
    for (const m of items) used.add(m.id);
    total += items.length;
    lines.push(`## ${cert.title} — ${items.length} problems`);
    lines.push("");
    lines.push("| Slug | Title | Difficulty | Duration |");
    lines.push("| --- | --- | --- | --- |");
    for (const m of items) {
      const enName = m.i18n?.en?.name ?? m.name;
      lines.push(
        `| \`${m.id}\` | ${enName} | ${m.difficulty} | ${m.estimatedDuration} |`,
      );
    }
    lines.push("");
  }

  const ungrouped = metas.filter((m) => !used.has(m.id));
  if (ungrouped.length > 0) {
    lines.push("## Other Challenges");
    lines.push("");
    lines.push("| Slug | Title | Difficulty | Duration |");
    lines.push("| --- | --- | --- | --- |");
    for (const m of ungrouped) {
      const enName = m.i18n?.en?.name ?? m.name;
      lines.push(`| \`${m.id}\` | ${enName} | ${m.difficulty} | ${m.estimatedDuration} |`);
    }
    lines.push("");
  }

  lines.push(`**Total certification Challenges: ${total}.**`);
  lines.push("");
  return `${lines.join("\n")}`;
}

function main(): void {
  const out = render(loadChallenges());
  if (process.argv.includes("--check")) {
    const current = readFileSync(OUT_PATH, "utf8");
    if (current !== out) {
      console.error("CERTIFICATION-INDEX.md is stale. Run: bun run scripts/build-cert-index.ts");
      process.exit(1);
    }
    console.log("CERTIFICATION-INDEX.md is up to date.");
    return;
  }
  writeFileSync(OUT_PATH, out);
  console.log("Wrote CERTIFICATION-INDEX.md.");
}

main();
