"""A tiny state machine, its execution trace, and the field the trace lives in.

The machine is deliberately small enough to write out by hand:

    a_{i+1} = a_i + b_i          (mod p)
    b_{i+1} = b_i + weight*a_i   (mod p)

Two columns, two transition rules, and a trace of `steps` rows. That is the whole
computation, and the point is not the computation -- it is that "proving this ran" turns
into "these polynomial relations vanish on these points", and that the translation loses
nothing only if every row is constrained.

The evaluation domain is the multiplicative subgroup generated by a root of unity of
order `steps`, which is what makes the vanishing polynomial X^steps - 1 and lets domain
points map to trace rows in order. Primes are chosen so that such a root exists.

Toy sizes throughout. This is a bridge to arithmetization, not a proof system: there is
no commitment, no randomness from a verifier, and nothing here is sound against anybody.
"""

from __future__ import annotations

import hashlib

# (p, steps): steps divides p-1, so a primitive steps-th root of unity exists in F_p.
DOMAINS = (
    (97, 8),
    (193, 8),
    (241, 8),
    (337, 16),
    (401, 16),
    (577, 16),
)


def _stream(seed: str, label: str) -> list[int]:
    out: list[int] = []
    counter = 0
    while len(out) < 96:
        out.extend(hashlib.sha256(f"{seed}:{label}:{counter}".encode()).digest())
        counter += 1
    return out


def _pick(s: list[int], i: int, low: int, high: int) -> int:
    return low + ((s[i % 90] * 256 + s[(i + 1) % 90]) % (high - low + 1))


def setting(seed: str, label: str = "public") -> dict:
    s = _stream(seed, f"setting:{label}")
    p, steps = DOMAINS[s[0] % len(DOMAINS)]
    return {
        "p": p,
        "steps": steps,
        "weight": _pick(s, 2, 1, p - 1),
        "start": (_pick(s, 4, 1, p - 1), _pick(s, 6, 1, p - 1)),
    }


def root_of_unity(p: int, order: int) -> int:
    """A generator of the order-`order` multiplicative subgroup of F_p."""
    exponent = (p - 1) // order
    for candidate in range(2, p):
        root = pow(candidate, exponent, p)
        if root != 1 and pow(root, order, p) == 1:
            if all(pow(root, order // factor, p) != 1 for factor in _prime_factors(order)):
                return root
    raise ValueError(f"no root of unity of order {order} in F_{p}")


def _prime_factors(n: int) -> set[int]:
    factors: set[int] = set()
    remaining = n
    factor = 2
    while factor * factor <= remaining:
        while remaining % factor == 0:
            factors.add(factor)
            remaining //= factor
        factor += 1
    if remaining > 1:
        factors.add(remaining)
    return factors


def domain(setting_dict: dict) -> list[int]:
    """The evaluation domain, in the order that matches trace rows."""
    p, steps = setting_dict["p"], setting_dict["steps"]
    root = root_of_unity(p, steps)
    return [pow(root, index, p) for index in range(steps)]


def honest_trace(setting_dict: dict) -> list[tuple[int, int]]:
    """What the machine actually did. The reference answer for the trace checkpoint."""
    p, steps, weight = setting_dict["p"], setting_dict["steps"], setting_dict["weight"]
    a, b = setting_dict["start"]
    rows = [(a % p, b % p)]
    for _ in range(steps - 1):
        a, b = (a + b) % p, (b + weight * a) % p
        rows.append((a, b))
    return rows


def tampered_trace(seed: str, label: str, setting_dict: dict) -> tuple[list[tuple[int, int]], int]:
    """An honest trace with exactly one row changed, and which row it was.

    The tampered row is never the first or the last: a tamper at the ends is caught by
    the boundary constraints alone, which would let an implementation that checks only
    boundaries look correct.
    """
    rows = [list(row) for row in honest_trace(setting_dict)]
    s = _stream(seed, f"tamper:{label}")
    steps, p = setting_dict["steps"], setting_dict["p"]
    index = _pick(s, 0, 1, steps - 2)
    column = s[4] % 2
    rows[index][column] = (rows[index][column] + 1 + _pick(s, 6, 0, p - 3)) % p
    return [tuple(row) for row in rows], index


def health_token(seed: str) -> str:
    cfg = setting(seed)
    return hashlib.sha256(f"health:{seed}:{cfg['p']}:{cfg['steps']}".encode()).hexdigest()[:16]


def public_payload(seed: str) -> dict[str, object]:
    """Everything a participant may see for this deployment. Carries values, not code.

    This is the `public` label only, and it is exactly what `make inspect` has always
    printed and what `tests/public/test_air.py` has always used: the setting, the
    evaluation domain, and the trace the machine produces from that setting. Every
    checkpoint is graded on the `h0`, `h1` and `h2` labels (see tests/hidden/check_air.py),
    and `transfer` on a different seed again, each of which derives a different prime, a
    different trace length, a different transition weight and a different starting state --
    so no value below narrows a graded run.

    Within the `public` label the trace travels as values because it always has: `make
    inspect` prints every row beside its domain point, and the recurrence that produces it
    is written out in `starter/air.py`, in this file's own module docstring and in the
    README. Handing over one label's rows is not handing over `execute`.

    What does not travel is the code. `honest_trace` -- which this module's own docstring
    calls the reference answer for the trace checkpoint -- and the seed derivation that
    decides the hidden labels stay in the verifier image, beside
    `tests/hidden/check_air.py`, which states the residual count, the row a transition
    failure is attributed to, and the four conditions an underconstrained witness is
    accepted on. Those are the things `starter/air.py` asks the learner to work out.
    """
    cfg = setting(seed)
    return {
        "healthToken": health_token(seed),
        "setting": {
            "p": cfg["p"],
            "steps": cfg["steps"],
            "weight": cfg["weight"],
            "start": list(cfg["start"]),
        },
        "domain": domain(cfg),
        "trace": [list(row) for row in honest_trace(cfg)],
    }
