// Independent reviewer suite, retained with import paths made portable; test logic unchanged.
import { test, expect } from 'bun:test';
import { initialState, applyOp, validateOp, execute, roles, projectForTeam, tick } from '../game/reducer.ts';
import { createLab } from '../dev/server.ts';
import type { State, Op } from '../game/types.ts';
let serial=0;
const state=()=>initialState({eventId:'independent-review',teamIds:['alpha','bravo'],matchSecret:'a'.repeat(64)});
const op=(s:State,team:string,payload:any)=>applyOp(s,team,{...payload,id:`op_${serial++}`,revision:s.revision} as Op);
function configured(controls:any[]=[]){let s=state();s=op(s,'alpha',{kind:'ready'});s=op(s,'bravo',{kind:'ready'});const r=roles(s);s=op(s,r.attacker,{kind:'try',action:'export',token:s.leak});s=op(s,r.attacker,{kind:'finish'});return op(s,r.defender,{kind:'defend',controls});}
test('server secret and two distinct seats are required',()=>{expect(()=>initialState({eventId:'x',teamIds:['a','a'],matchSecret:'a'.repeat(64)})).toThrow();expect(()=>initialState({eventId:'x',teamIds:['a','b']})).toThrow();});
test('unknown teams and client-provided authority fields are rejected',()=>{const s=configured();expect(validateOp(s,'stranger',{kind:'legitimate',id:'x',revision:s.revision}).ok).toBe(false);expect(validateOp(s,'bravo',{kind:'try',action:'addAdmin',token:s.leak,reauthenticated:true,id:'x',revision:s.revision}).ok).toBe(false);});
test('team roles do not cross operation boundaries',()=>{const s=configured();const {defender,attacker}=roles(s);expect(validateOp(s,attacker,{kind:'legitimate',id:'x',revision:s.revision}).ok).toBe(false);expect(validateOp(s,defender,{kind:'try',action:'export',token:s.leak,id:'x',revision:s.revision}).ok).toBe(false);});
test('forged opaque grant IDs cannot satisfy authorization',()=>{const s=configured(['stepUp','approval']);expect(execute(s,s.leak,'addAdmin','lab_grant_forged','lab_grant_forged')).toBe('reauth_required');const a=configured(['approval']);expect(execute(a,a.leak,'addAdmin',undefined,'lab_grant_forged')).toBe('approval_required');});
test('grants bind session, action, round, expiry and issuer',()=>{for(const patch of [{token:'other'},{action:'spend'},{round:2},{expires:0},{issuer:'reviewer'},{consumed:true}]){const s=configured(['stepUp']);s.grants.push({id:'owner_grant',token:s.leak,action:'addAdmin',round:1,expires:100,consumed:false,issuer:'owner',...patch} as any);expect(execute(s,s.leak,'addAdmin','owner_grant')).toBe('reauth_required');}});
test('required grants are consumed only after all checks pass and once',()=>{const s=configured(['stepUp','approval']);s.grants.push({id:'owner',token:s.leak,action:'addAdmin',round:1,expires:100,consumed:false,issuer:'owner'});expect(execute(s,s.leak,'addAdmin','owner')).toBe('approval_required');expect(s.grants[0].consumed).toBe(false);s.grants.push({id:'reviewer',token:s.leak,action:'addAdmin',round:1,expires:100,consumed:false,issuer:'reviewer'});expect(execute(s,s.leak,'addAdmin','owner','reviewer')).toBe('executed');expect(execute(s,s.leak,'addAdmin','owner','reviewer')).toBe('reauth_required');});
test('short expiry denies precisely at boundary, retains earlier damage',()=>{let s=configured(['shortTTL']);s=op(s,roles(s).attacker,{kind:'try',action:'export',token:s.leak});s=tick(s,15000);expect(execute(s,s.leak,'addAdmin')).toBe('expired');expect(s.damage).toBe(20);});
test('revocation is enforced by server state',()=>{const s=configured(['revoke']);expect(execute(s,s.leak,'export')).toBe('revoked');});
test('initial-login and HttpOnly models do not magically prevent token reuse',()=>{const s=configured(['strongLogin','httpOnly']);expect(execute(s,s.leak,'addAdmin')).toBe('executed');});
test('tokens cannot be reused across distinct matches',()=>{const s=configured();const other=initialState({eventId:'independent-review',teamIds:['alpha','bravo'],matchSecret:'b'.repeat(64)});expect(execute(other,s.leak,'export')).toBe('invalid_session');});
test('duplicate exact request is idempotent; changed payload and stale revision reject',()=>{let s=configured();const request={kind:'try',action:'export',token:s.leak,id:'same',revision:s.revision} as Op;const t=applyOp(s,'bravo',request);expect(applyOp(t,'bravo',request)).toBe(t);expect(t.damage).toBe(20);expect(validateOp(t,'bravo',{...request,action:'spend'}).ok).toBe(false);expect(validateOp(t,'bravo',{...request,id:'new'}).ok).toBe(false);});
test('defender projection excludes session tokens; both projections exclude grants, receipts and secret',()=>{const s=configured(['stepUp']);for(const team of s.ids){const p=JSON.stringify(projectForTeam(s,team));expect(p).not.toContain(s.secret);expect(p).not.toContain('lab_grant_');expect(p).not.toContain('receipts');}expect(JSON.stringify(projectForTeam(s,'alpha'))).not.toContain(s.leak);});
test('attacker cannot settle before legitimate action; later action settles exactly once',()=>{let s=configured(['revoke']);s=op(s,'bravo',{kind:'finish'});expect(s.results).toHaveLength(0);expect(s.attackFinished).toBe(true);s=op(s,'alpha',{kind:'legitimate'});expect(s.results).toHaveLength(1);expect(s.results[0].defensePoints).toBe(94);});
test('API rejects foreign host, origin, absent seat and forged seat',async()=>{const lab=createLab({clock:()=>0});for(const request of [new Request('http://attacker.invalid/api/projection'),new Request('http://localhost/api/projection',{headers:{origin:'https://attacker.invalid'}}),new Request('http://localhost/api/projection'),new Request('http://localhost/api/projection',{headers:{authorization:'Seat forged'}})])expect((await lab.handler(request)).status).toBeGreaterThanOrEqual(400);});
test('HTTP seat identity is independent of game token',async()=>{const lab=createLab({clock:()=>0});const response=await lab.handler(new Request('http://localhost/api/projection',{headers:{authorization:`Seat ${lab.seats.alpha}`}}));expect(response.status).toBe(200);expect((await response.json()).projection.me).toBe('alpha');expect((await lab.handler(new Request('http://localhost/api/projection',{headers:{authorization:'Seat lab_session_forged'}}))).status).toBe(401);});
test('API rejects malformed JSON and request above 4096 bytes',async()=>{const lab=createLab({clock:()=>0});const headers={authorization:`Seat ${lab.seats.alpha}`,'content-type':'application/json'};expect((await lab.handler(new Request('http://localhost/api/op',{method:'POST',headers,body:'{'}))).status).toBe(400);expect((await lab.handler(new Request('http://localhost/api/op',{method:'POST',headers,body:'x'.repeat(4097)}))).status).toBe(413);});
test('legitimate reviewed admin path uses action-bound server grants, does not reveal them',()=>{let s=configured(['stepUp','approval']);s=op(s,'alpha',{kind:'legitimate'});expect(s.events.at(-1)?.result).toBe('reviewer_success');expect(s.desk.admins).toContain('fictional-reviewed-admin');const admin=s.grants.filter(g=>g.action==='addAdmin');expect(admin).toHaveLength(2);expect(admin.every(g=>g.consumed)).toBe(true);for(const team of s.ids){const p=JSON.stringify(projectForTeam(s,team));for(const g of s.grants)expect(p).not.toContain(g.id);}expect(execute(s,s.leak,'addAdmin',admin[0].id,admin[1].id)).toBe('reauth_required');});
test('reviewer approval cannot override least-privilege denial',()=>{let s=configured(['approval','leastPrivilege']);s=op(s,'alpha',{kind:'legitimate'});expect(s.events.at(-1)?.result).toBe('role_denied');expect(s.desk.admins).not.toContain('fictional-reviewed-admin');expect(s.legitimate).toBe(true);});
